export default {
  state: {
  branches: [
    { name: 'Basics',
      description: 'HTML, CSS and JavaScript will to you the world of Web Development.',
      id: 'basics',
      leafs: [
        { name: 'HTML', ripple: 'orange--text', logo: 'https://www.shareicon.net/download/2015/09/08/97875_html_512x512.png', to: 'html', title: 'HTML - HyperText Markup Language', whatIsVideo: 'https://www.youtube.com/embed/3V2q5E4wwko', todo: false, starred: false, shared: false,
          sources: [
            { name: 'SoloLearn',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.sololearn.com/Course/HTML/',
              logo: 'http://mrslamarche.com/wp-content/uploads/2016/08/com.sololearn.htmltrial-w250.png',
              icon: 'devices' },

            { name: 'Khanacademy',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.khanacademy.org/computing/computer-programming/html-css/#intro-to-html',
              logo: 'https://cdn.kastatic.org/images/avatars/svg/leaf-green.svg',
              icon: 'devices' },

            { name: 'W3schools',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.w3schools.com/html/',
              logo: 'https://store-images.s-microsoft.com/image/apps.30495.13510798887792718.c58f517f-a070-448d-9f42-44c93b19dcae.05c3b4ed-79d8-4d84-be6d-7d3290f1533e?w=180&h=180&q=60',
              icon: 'library_books' },

            { name: 'MDN',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
              logo: 'https://mdn.mozillademos.org/files/6457/mdn_logo_only_color.png',
              icon: 'library_books' },

            { name: 'Stefan Mischook',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.youtube.com/watch?v=dIik9qnnSQA&list=PL4WWE_tMSca2ud8vp2cdtLsv3yADiJPiR',
              logo: 'http://www.stickpng.com/assets/images/580b57fcd9996e24bc43c548.png',
              icon: 'video_library' },

            { name: 'The Net Ninja',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.youtube.com/watch?v=Y1BlT4_c_SU&list=PL4cUxeGkcC9ibZ2TSBaGGNrgh4ZgYE6Cc',
              logo: 'https://yt3.ggpht.com/a-/AJLlDp2oM9rg7DFu7iit71Ndh0yNIEL7F_j0VCRWuQ=s900-mo-c-c0xffffffff-rj-k-no',
              icon: 'video_library' },

            { name: 'Academind',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.youtube.com/watch?v=OxOx3WI3Df4&list=PL55RiY5tL51rv_vo3TM3Byu71RYchX_l_',
              logo: 'https://academind.com/images/academind-logo.png',
              icon: 'video_library' },

            { name: 'Udemy',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.udemy.com/courses/search/?q=HTML',
              logo: 'https://cdn.worldvectorlogo.com/logos/udemy-1.svg',
              icon: 'attach_money' },

            { name: 'Treehouse',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://teamtreehouse.com/learn/html?utm_source=google&cid=1352&utm_source=google&campaign=791365357&utm_term=&cid=1352&gclid=Cj0KCQiA2Y_UBRCGARIsALglqQ1V2_6236fYn3EADbp31WZ7M3XfT3rUIHZXnJJilsuq6vvj8-_DFbgaAkJHEALw_wcB&gclsrc=aw.ds',
              logo: 'https://davidwalsh.name/demo/treehouse-logo.png',
              icon: 'attach_money' },

            { name: 'Codecademy',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.codecademy.com/learn/learn-html',
              logo: 'https://cdn-images-1.medium.com/max/2000/1*eAkVW2LFAd9pKdL-8hBQ1A.png',
              icon: 'attach_money' },

            { name: 'in Learning',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.linkedin.com/learning/topics/html',
              logo: 'https://lh3.googleusercontent.com/WGnfuvo95Yporu_v1zBaDDpt5RLYh_eM1YMMu56pos4V81Ae2djhMfTPtAI50DhLglT4=w300',
              icon: 'attach_money' },

            { name: 'Plurasight',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.pluralsight.com/paths/html5',
              logo: 'https://images-na.ssl-images-amazon.com/images/I/51-Hci2bYjL.png',
              icon: 'attach_money' }
            ]
        },
        { name: 'CSS', ripple: 'blue--text', logo: 'https://www.shareicon.net/download/2015/09/08/97876_css_512x512.png', to: 'css', title: 'CSS - Cascading Style Sheets', whatIsVideo: 'https://www.youtube.com/embed/ua3Y-X6-WQc', todo: false, starred: false, shared: false,
          sources: [
            { name: 'SoloLearn',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.sololearn.com/Course/CSS/',
              logo: 'https://lh3.googleusercontent.com/UAylvT-lNL3zfIefMgP9kiUwrhEnJxJiwq8hC0kne0qvSaOGYH8BVlJMYnNWRneb5AI=w300',
              icon: 'devices' },

            { name: 'Khanacademy',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.khanacademy.org/computing/computer-programming/html-css/#intro-to-css',
              logo: 'https://cdn.kastatic.org/images/avatars/svg/leaf-green.svg',
              icon: 'devices' },

            { name: 'W3schools',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.w3schools.com/css/',
              logo: 'https://store-images.s-microsoft.com/image/apps.30495.13510798887792718.c58f517f-a070-448d-9f42-44c93b19dcae.05c3b4ed-79d8-4d84-be6d-7d3290f1533e?w=180&h=180&q=60',
              icon: 'library_books' },

            { name: 'MDN',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
              logo: 'https://mdn.mozillademos.org/files/6457/mdn_logo_only_color.png',
              icon: 'library_books' },

            { name: 'The Net Ninja',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.youtube.com/watch?v=I9XRrlOOazo&feature=youtu.be&list=PL4cUxeGkcC9gQeDH6xYhmO-db2mhoTSrT',
              logo: 'https://yt3.ggpht.com/a-/AJLlDp2oM9rg7DFu7iit71Ndh0yNIEL7F_j0VCRWuQ=s900-mo-c-c0xffffffff-rj-k-no',
              icon: 'video_library' },

            { name: 'Academind',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.youtube.com/watch?v=zwgSc3EntWM&index=5&list=PL55RiY5tL51rv_vo3TM3Byu71RYchX_l_',
              logo: 'https://academind.com/images/academind-logo.png',
              icon: 'video_library' },

            { name: 'Stefan Mischook',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://youtu.be/CfyafrlGRzE?list=PL4WWE_tMSca2Oh4MEAfzLU6T7_yWmg0qY',
              logo: 'http://www.stickpng.com/assets/images/580b57fcd9996e24bc43c548.png',
              icon: 'video_library' },

            { name: 'Udemy',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.udemy.com/courses/search/?q=CSS',
              logo: 'https://cdn.worldvectorlogo.com/logos/udemy-1.svg',
              icon: 'attach_money' },

            { name: 'Codecademy',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.codecademy.com/learn/learn-css',
              logo: 'https://cdn-images-1.medium.com/max/2000/1*eAkVW2LFAd9pKdL-8hBQ1A.png',
              icon: 'attach_money' },

            { name: 'Treehouse',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://teamtreehouse.com/learn/css?utm_source=google&cid=1352&utm_source=google&campaign=791365357&utm_term=&cid=1352&gclid=Cj0KCQiA2Y_UBRCGARIsALglqQ1V2_6236fYn3EADbp31WZ7M3XfT3rUIHZXnJJilsuq6vvj8-_DFbgaAkJHEALw_wcB&gclsrc=aw.ds',
              logo: 'https://davidwalsh.name/demo/treehouse-logo.png',
              icon: 'attach_money' },

            { name: 'in Learning',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.linkedin.com/learning/topics/css',
              logo: 'https://lh3.googleusercontent.com/WGnfuvo95Yporu_v1zBaDDpt5RLYh_eM1YMMu56pos4V81Ae2djhMfTPtAI50DhLglT4=w300',
              icon: 'attach_money' },

            { name: 'Plurasight',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.pluralsight.com/paths/css',
              logo: 'https://images-na.ssl-images-amazon.com/images/I/51-Hci2bYjL.png',
              icon: 'attach_money' }
            ]
        },
        { name: 'JavaScript', ripple: 'yellow--text', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png', to: 'javascript', title: 'JavaScript - response and interactivity.', whatIsVideo: 'https://www.youtube.com/embed/AgrWeFJWRTg', todo: false, starred: false, shared: false,
          sources: [
            { name: 'SoloLearn',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.sololearn.com/Course/JavaScript/',
              logo: 'https://lh3.googleusercontent.com/VMhNdwD6dEukMpEoX9muTVHfdNdR61_isd0VWongciNOUQjQ5Zlm5habSTplvQM3J00=w300',
              icon: 'devices' },


            { name: 'W3schools',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.w3schools.com/js/',
              logo: 'https://store-images.s-microsoft.com/image/apps.30495.13510798887792718.c58f517f-a070-448d-9f42-44c93b19dcae.05c3b4ed-79d8-4d84-be6d-7d3290f1533e?w=180&h=180&q=60',
              icon: 'library_books' },

            { name: 'MDN',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
              logo: 'https://mdn.mozillademos.org/files/6457/mdn_logo_only_color.png',
              icon: 'library_books' },

            { name: 'The Net Ninja',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.youtube.com/watch?v=I9XRrlOOazo&feature=youtu.be&list=PL4cUxeGkcC9gQeDH6xYhmO-db2mhoTSrT',
              logo: 'https://yt3.ggpht.com/a-/AJLlDp2oM9rg7DFu7iit71Ndh0yNIEL7F_j0VCRWuQ=s900-mo-c-c0xffffffff-rj-k-no',
              icon: 'video_library' },

            { name: 'Academind',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.youtube.com/watch?v=_mj72QqsOs4&feature=youtu.be',
              logo: 'https://academind.com/images/academind-logo.png',
              icon: 'video_library' },

            { name: 'Traversy Media',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.youtube.com/watch?v=vEROU2XtPR8',
              logo: 'https://yt3.ggpht.com/a-/AJLlDp1dGyGeP0kf7oj9ykar-Mb2I2O8c8KyrEgIbg=s900-mo-c-c0xffffffff-rj-k-no',
              icon: 'video_library' },

            { name: 'Udemy',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.udemy.com/courses/search/?q=Javascript&src=ukw&p=1&courseLabel=8322',
              logo: 'https://cdn.worldvectorlogo.com/logos/udemy-1.svg',
              icon: 'attach_money' },

            { name: 'Codecademy',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.codecademy.com/learn/introduction-to-javascript',
              logo: 'https://cdn-images-1.medium.com/max/2000/1*eAkVW2LFAd9pKdL-8hBQ1A.png',
              icon: 'attach_money' },

            { name: 'Treehouse',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://teamtreehouse.com/learn/javascript?utm_source=google&cid=1352&utm_source=google&campaign=791365357&utm_term=&cid=1352&gclid=Cj0KCQiA2Y_UBRCGARIsALglqQ1V2_6236fYn3EADbp31WZ7M3XfT3rUIHZXnJJilsuq6vvj8-_DFbgaAkJHEALw_wcB&gclsrc=aw.ds',
              logo: 'https://davidwalsh.name/demo/treehouse-logo.png',
              icon: 'attach_money' },

            { name: 'in Learning',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.linkedin.com/learning/topics/javascript',
              logo: 'https://lh3.googleusercontent.com/WGnfuvo95Yporu_v1zBaDDpt5RLYh_eM1YMMu56pos4V81Ae2djhMfTPtAI50DhLglT4=w300',
              icon: 'attach_money' },

            { name: 'Plurasight',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.pluralsight.com/paths/javascript',
              logo: 'https://images-na.ssl-images-amazon.com/images/I/51-Hci2bYjL.png',
              icon: 'attach_money' }
          ]
        },
        { name: 'Node.js',
          ripple: 'lime--text',
          logo: 'http://blog.iampuneet.in/wp-content/uploads/2017/06/nodejs_logo.png',
          to: 'nodejs',
          title: 'Node.js - javascript for the server side',
          whatIsVideo: 'https://www.youtube.com/embed/lNiGH21gMiw?list=PL55RiY5tL51qXR-9ypW3HyzyWKpuuglKg',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'Webpack',
          ripple: 'light-blue--text',
          logo: 'https://topheman.github.io/webpack-babel-starter/assets/974262647c82057b6078c432841a53ea.png',
          to: 'webpack',
          title: 'Webpack - bundle your files!',
          whatIsVideo: 'https://www.youtube.com/embed/5zeXFC_-gMQ',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'CLI',
          ripple: 'black--text',
          logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Icons8_flat_command_line.svg/2000px-Icons8_flat_command_line.svg.png',
          to: 'command_line',
          title: 'CLI - Command Line Interface',
          whatIsVideo: '',
          sources: [''] },
        { name: 'Components',
          ripple: 'orange--text',
          logo: 'https://raw.githubusercontent.com/webcomponents/webcomponents-icons/master/logo/logo_256x256.png',
          to: 'components',
          title: '',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: [''] }
      ]
    },
    { name: 'Frontend',
      description: 'Templating, compiling and CSS extentions!',
      id: 'frontend',
      leafs: [
        { name: 'Haml',
          ripple: 'white--text',
          logo: 'https://codekitapp.com/images/help/free-haml-icon@2x.png',
          to: 'haml',
          title: 'Beautiful, DRY, well-indented, clear markup: templating haiku.',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'Slim',
          ripple: 'grey--text',
          logo: 'http://ahoylemon.github.io/minnebar2016/img/slim.png',
          to: 'slim',
          title: 'A lightweight templating engine',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'Markdown',
          ripple: 'grey--text',
          logo: 'https://pbs.twimg.com/profile_images/425948730/DF-Star-Logo.png',
          to: 'markdown',
          title: 'Markdown is a text-to-HTML conversion tool for web writers.',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'Pug',
          ripple: 'white--text',
          logo: 'https://amandeepmittal.gallerycdn.vsassets.io/extensions/amandeepmittal/pug/1.0.1/1509818475774/Microsoft.VisualStudio.Services.Icons.Default',
          to: 'pug',
          title: 'Pug is a template engine for Node.js.',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'SASS',
          ripple: 'pink--text',
          logo: 'http://sass-lang.com/assets/img/styleguide/seal-color-aef0354c.png',
          to: 'sass',
          title: 'SASS - Syntactically Awesome Style Sheets.',
          whatIsVideo: 'http://files3.lynda.com/secure/courses/536431/VBR_MP4h264_main_SD/536431_01_01_XR30_whatissass.mp4?WRntSYywIn1-InSo9r0DPhT0iDlPiv7ge30qLaO8waITLR687zhL0_3MajwWLdVuSSd-ZPYdFlIVIucyZc2Eoq-xYSz4dtoodMst3SEhMV0fjkwxy3xSWr0tirAGz6XAPZxhxBJNkLwtA44xS4oksIpGmsKgaEWxyMqvpjwt2aBkZoLQ1je7tmmSOBruQnU&c3.ri=3773640875087086116',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'Less',
          ripple: 'blue--text',
          logo: 'https://cdn-images-1.medium.com/max/1600/1*O_NwDtfHb1sirw6CAbyoxg.png',
          to: 'less',
          title: 'It\'s CSS, with just a little more.',
          whatIsVideo: '',
          sources: [''] },
        { name: 'PostCSS',
          ripple: 'red--text',
          logo: 'http://postcss.org/_/web_modules/Hero/postcss.svg',
          to: 'postcss',
          title: 'A tool for transforming CSS with JavaScript',
          whatIsVideo: '',
          sources: [''] },
        { name: 'Stylus',
          ripple: 'black--text',
          logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFN9wkn14itSWP4vko1WclfxVkjj1GZ-tFGB0APoh6GddYDlbp',
          to: 'stylus',
          title: 'EXPRESSIVE, DYNAMIC, ROBUST CSS',
          whatIsVideo: '',
          sources: [''] },
        { name: 'JQuery',
          ripple: 'green--text',
          logo: 'http://ethiopiarabb.com/assets/images/icon-jquery.png',
          to: 'jquery',
          title: 'jQuery - a lightweight javascript library',
          whatIsVideo: 'https://www.youtube.com/embed/U4UZVbQ8md0',
          todo: false,
          starred: false,
          shared: false,
          sources: [
            { name: 'JQuery',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://jquery.com/',
              logo: 'https://js.foundation/wp-content/uploads/sites/33/2017/02/jquery.png',
              icon: 'description' },

            { name: 'SoloLearn',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.sololearn.com/Course/jQuery/',
              logo: 'https://lh3.googleusercontent.com/ETvE8qpSRnKBb7QMEkctSfC8r3CjGmMy00PtV3qq0YLUVl1PtKjTVpGXCP8cO9xnGw=w300',
              icon: 'devices' },

            { name: 'in Learning',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.linkedin.com/learning/topics/jquery',
              logo: 'https://lh3.googleusercontent.com/WGnfuvo95Yporu_v1zBaDDpt5RLYh_eM1YMMu56pos4V81Ae2djhMfTPtAI50DhLglT4=w300',
              icon: 'attach_money' },

            { name: 'Plurasight',
              todo: false,
              starred: false,
              shared: false,
              link: 'https://www.pluralsight.com/paths/jquery',
              logo: 'https://images-na.ssl-images-amazon.com/images/I/51-Hci2bYjL.png',
              icon: 'attach_money' }
          ]  },
        { name: 'ECMAScript',
          ripple: 'yellow--text',
          logo: 'https://codereviewvideos.com/blog/wp-content/uploads/2016/04/es6-logo.png',
          to: 'es6',
          title: '',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'Babel',
          ripple: 'yellow--text',
          logo: 'https://cdn-images-1.medium.com/max/800/1*58R0tzuzVXd_7k89Igm9jA.png',
          to: 'babel',
          title: 'Use next generation JavaScript, today.',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'TypeScript',
          ripple: 'blue--text',
          logo: 'https://lh3.googleusercontent.com/-A0wE9U2zDI0/WJY7M98lmEI/AAAAAAAAcQo/-KHSsKPozoQw1USqlSqlaP3GDBhCFyAqwCE0/s1024/ts.png',
          to: 'ts',
          title: '',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'CofeeScript',
          ripple: 'blue-grey--text',
          logo: 'https://cdn.worldvectorlogo.com/logos/coffeescript.svg',
          to: 'cofeescript',
          title: 'CoffeeScript is a little language that compiles into JavaScript.',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  },
        { name: 'LiveScript',
          ripple: 'light-blue--text',
          logo: 'https://avatars3.githubusercontent.com/u/25471216?s=200&v=4',
          to: 'cofeescript',
          title: 'LiveScript is a language which compiles to JavaScript.',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']  }
      ]
    },
    { name: 'Backend',
      description: 'Control and manage data on your page.',
      id: 'backend',
      leafs: [
        { ripple: 'blue--text', logo: 'https://sipexa.com/wp-content/uploads/php-logo.png', name: 'PHP', to: 'php' },
        { ripple: 'blue--text', logo: 'https://e-mc2.net/sites/default/files/articles/SQL_2.png', name: 'SQL', to: 'sql' },
        { ripple: 'light-blue--text', logo: 'http://provp.sd-grp.com/wp-content/uploads/2014/03/ASP-NET-LOGO.png', name: 'ASP.NET', to: 'asp' },
        { ripple: 'yellow--text', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/2000px-Python-logo-notext.svg.png', name: 'Python', to: 'python' },
        { ripple: 'red--text', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/2000px-Ruby_logo.svg.png', name: 'Ruby', to: 'ruby' },
        { ripple: 'amber--text', logo: 'https://firebase.google.com/_static/images/firebase/touchicon-180.png', name: 'Firebase', to: '/firease' },
        { name: 'Symfony', ripple: 'black--text', logo: 'https://symfony.com/images/v5/pictos/home-main-illu.svg', to: 'symfony' },
        { name: 'Django', ripple: 'green--text', logo: 'http://www.unixstickers.com/image/data/buttons/png/django.png', to: 'django' },
        { name: 'Laravel', ripple: 'red--text', logo: 'http://www.stickpng.com/assets/images/58480e35cef1014c0b5e4920.png', to: 'laravel' },
        { name: 'Ruby On Rails', ripple: 'red--text', logo: 'https://upload.wikimedia.org/wikipedia/commons/1/16/Ruby_on_Rails-logo.png', to: 'rails' }
      ]
    },
    { name: 'Frameworks',
      description: 'Make JavaScript running faster with JavaScript Frameworks!',
      id: 'frameworks',
      leafs: [
        { name: 'Vue',
          logo: 'http://blog.evanyou.me/images/logo.png',
          ripple: 'teal--text',
          to: 'vue',
          title: 'Vue.js - progressive framework for building user interfaces.',
          whatIsVideo: 'https://www.youtube.com/embed/3I8EFGIORRc',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']},
        { name: 'Angular',
          logo: 'https://cdn.worldvectorlogo.com/logos/angular-icon-1.svg',
          ripple: 'red--text',
          to: 'angular',
          title: 'Angular - makes it easy to build applications with the web.',
          whatIsVideo: 'https://www.youtube.com/embed/b9gnX62ZMTU',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']},
        { name: 'React',
          logo: 'https://sandstorm.de/_Resources/Persistent/3285416e8503b2c8354c321bcd690cf550b8b2d3/React-Logo.svg',
          ripple: 'light-blue--text',
          to: 'react',
          title: 'React - A JavaScript library for building user interfaces.',
          whatIsVideo: 'https://www.youtube.com/embed/OUSz_24ljgY',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']},
        { name: 'Preact',
          logo: 'https://seeklogo.com/images/P/preact-logo-64E4BF9ABC-seeklogo.com.png',
          ripple: 'purple--text',
          to: 'preact',
          title: 'Preact - Fast 3kB alternative to React with the same modern API.',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']},
        { name: 'Ember',
          logo: 'http://emberjs.com/images/tomster-sm.png',
          ripple: 'orange--text',
          to: 'ember',
          title: 'Ember - for creating ambitious web applications.',
          whatIsVideo: 'https://files3.lynda.com/secure/courses/178116/VBR_MP4h264_main_SD/178116_01_01_XR15_whatis.mp4?HqLkriiSiQYNTpjq6quDEUnuw88KP9x-wuiHWMZsXbEQHyHLJwVntUGFsromh6P2O-03G2Ek8oxPSmSgG5Rx_2Xb5XI1UrmKQcC32lLIwdZTdu4YOP9oIRRRtPrQ-VeApym7azoloxcNMj0AF0K2gr9lPn08ftlwgnDbin1iBkcimLVFhw',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']},
        { name: 'Polymer',
          logo: 'https://avatars3.githubusercontent.com/u/2159051?v=4',
          ripple: 'blue--text',
          to: 'polymer',
          title: 'Unlock the Power of Web Components with Polymer.',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']},
        { name: 'Meteor',
          logo: 'http://www.stickpng.com/assets/images/58480fcfcef1014c0b5e4942.png',
          ripple: 'red--text',
          to: 'meteor',
          title: 'Meteor - the fastest way to build JavaScript Apps.',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']},
        { name: 'Aurelia',
          logo: 'https://user-images.githubusercontent.com/4623561/34425378-352f12c4-ebf9-11e7-86e2-8f20b8693bf5.png',
          ripple: 'pink--text',
          to: 'aurelia',
          title: '',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']},
        { name: 'Hugo',
          logo: 'https://gutl.jovenclub.cu/wp-content/uploads/2016/02/apple-touch-icon.png',
          ripple: 'pink--text',
          to: 'hugo',
          title: 'The world’s fastest framework for building websites',
          whatIsVideo: '',
          todo: false,
          starred: false,
          shared: false,
          sources: ['']}
      ]
    },
    { name: 'Libraries',
      description: 'Add awesome styles and components with CSS Libraries.',
      id: 'libraries',
      leafs: [
        { ripple: 'deep-purple--text', logo: 'https://getbootstrap.com/assets/img/bootstrap-stack.png', name: 'Bootstrap', to: '/html' },
        { ripple: 'black--text', logo: 'https://www.3pillarglobal.com/wp-content/uploads/2015/10/mdl_logo_320x260-300x260.png', name: 'Material Lite', to: '/mdl' },
        { ripple: 'pink--text', logo: 'http://materializecss.com/images/favicon/apple-touch-icon-152x152.png', name: 'Materialize', to: '/html' },
        { ripple: 'teal--text', logo: 'https://jgthms.com/web-design-in-4-minutes/bulma.png', name: 'Bulma', to: '/bulma' },
        { ripple: 'teal--text', logo: 'https://cdn.worldvectorlogo.com/logos/semantic-ui.svg', name: 'Semantic UI', to: '/html' },
        { ripple: 'red--text', logo: 'https://s3.amazonaws.com/media-p.slid.es/uploads/344767/images/2769652/g7.png', name: 'Onsen UI', to: '/onsenui' },
        { ripple: 'blue--text', logo: 'https://pbs.twimg.com/profile_images/818852933483823104/YYr9qgV8_400x400.jpg', name: 'UIkit', to: '/uikit' },
        { ripple: 'light-blue--text', logo: 'http://www.developersfeed.com/wp-content/uploads/2016/02/pure-css-logo-e1455594006843.png', name: 'Pure CSS', to: '/pure' },
        { ripple: 'light-blue--text', logo: 'http://element.eleme.io/1.4/static/banner-bg.75437e1.svg', name: 'Element', to: '/element' },
//VueLibs
        { ripple: 'teal--text', logo: 'https://bootstrap-vue.js.org/_nuxt/img/icon.f0a8c9e.png', name: 'Vue+Bootstrap', to: '/html' },
        { ripple: 'light-green--text', logo: 'https://camo.githubusercontent.com/55e8a928e9fca0eeb4e7cb7836cb60dc05703c65/68747470733a2f2f7675656d6174657269616c2e696f2f6173736574732f6c6f676f2d636f6c6f722e706e67', name: 'Vue-Material', to: '/vue-material' },
        { ripple: 'blue--text', logo: 'https://next.vuetifyjs.com/static/apple-touch-icon-180x180.png', name: 'Vuetify', to: '/html' },
        { ripple: 'purple--text', logo: 'https://avatars3.githubusercontent.com/u/26799900?s=400&v=4', name: 'Buefy', to: '/buefy' },
        { ripple: 'teal--text', logo: 'https://semantic-ui-vue.github.io/static/images/logo.png', name: 'Semantic UI Vue', to: '/html' },
        { ripple: 'white--text', logo: 'https://avatars2.githubusercontent.com/u/19988804?s=400&v=4', name: 'Vuikit', to: '/uikit' },
        { ripple: 'red--text', logo: 'https://s3.amazonaws.com/media-p.slid.es/uploads/344767/images/2769652/g7.png', name: 'Onsen UI', to: '/onsenui' },
        { ripple: 'purple--text', logo: 'https://madewithvuejs.com/uploads/07/11/vuesax.png', name: 'Vuesax', to: '/vuesax' },
//ReactLibs
        { ripple: 'light-blue--text', logo: 'https://qph.ec.quoracdn.net/main-qimg-a1cba7ee0601b2ea0bd44d7900e23cc8', name: 'Bootstrap', to: '/html' },
        { ripple: 'light-blue--text', logo: 'https://material-ui-next.com/static/brand.png', name: 'Material UI', to: '/html' },
        { ripple: 'white-text', logo: 'https://avatars1.githubusercontent.com/u/10089934?s=280&v=4', name: 'Materialize', to: '/html' },
        { ripple: 'lime--text', logo: 'https://react.semantic-ui.com/logo.png', name: 'Semantic', to: '/html' },
        { ripple: 'blue--text', logo: 'https://uikit-react.io/logo.svg?v2', name: 'UIkit-React', to: '/html' },
        { ripple: 'red--text', logo: 'https://s3.amazonaws.com/media-p.slid.es/uploads/344767/images/2769652/g7.png', name: 'Onsen UI', to: '/onsenui' },
//AngularLibs
        { ripple: 'blue--text', logo: 'https://ng-bootstrap.github.io/img/logo.svg', name: 'ng-Bootstrap', to: '/html' },
        { ripple: 'indigo--text', logo: 'http://angularexpo.com/content/images/2016/11/icon_192.png', name: 'ng-Material', to: '/html' },
        { ripple: 'orange--text', logo: 'https://cdn-images-1.medium.com/max/1600/1*ZPOa0Nn_fk0XtNTmeESQzA.png', name: 'Teradata', to: '/teradata' },
        { ripple: 'teal--text', logo: 'https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/e4/f0/c5/e4f0c5d3-da4f-0388-8da8-865f3b6a48c2/AppIcon-1x_U007emarketing-85-220-0-1.png/1200x630bb.jpg', name: 'ng-Semantic', to: '/ng-semantic' },
        { ripple: 'red--text', logo: 'https://www.primefaces.org/presskit/primeng-logo.png', name: 'PrimeNG', to: '/primeng' },
        { ripple: 'red--text', logo: 'https://s3.amazonaws.com/media-p.slid.es/uploads/344767/images/2769652/g7.png', name: 'Onsen UI', to: '/onsenui' },
        { ripple: 'orange--text', logo: 'https://habrastorage.org/webt/59/f0/51/59f05155beffd369502984.png', name: 'Clarity', to: '/clarity' }
      ]
    },
    { name: 'Graphics',
      description: 'That\'s about drawing things',
      id: 'graphics',
      leafs: [
        { ripple: 'amber--text', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/SVG_Logo.svg/2000px-SVG_Logo.svg.png', name: 'SVG', to: '/svg' },
        { ripple: 'orange--text', logo: 'https://library.uoregon.edu/sites/default/files/canvasicon_0.png', name: 'Canvas', to: '/canvas' },
        { ripple: 'red--text', logo: 'https://1001freedownloads.s3.amazonaws.com/vector/thumb/74145/iOS_7_Icon_Template.png', name: 'WebGL', to: '/webgl' },
        { ripple: 'white--text', logo: 'https://kenoleon.github.io/Front-End-Web-Dev-UI-UX/assets/images/threejsLogo.jpg', name: 'Three.js', to: '/threejs' },
        { ripple: 'light-blue--text', logo: 'https://assets.hongkiat.com/uploads/javascript-libraries-animate-svg/svg-vivus.jpg', name: 'Vivus.js', to: 'http://maxwellito.github.io/vivus/' },
        { ripple: 'indigo--text', logo: 'https://assets.hongkiat.com/uploads/javascript-libraries-animate-svg/svg-bonsai.jpg', name: 'Bonsai.js', to: 'http://bonsaijs.org/' },
        { ripple: 'indigo--text', logo: 'https://assets.hongkiat.com/uploads/javascript-libraries-animate-svg/svg-velocity.jpg', name: 'Velocity.js', to: 'http://velocityjs.org/' },
        { ripple: 'orange--text', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Rapha%C3%ABl_logo.svg/2000px-Rapha%C3%ABl_logo.svg.png', name: 'Raphaël.js', to: 'http://dmitrybaranovskiy.github.io/raphael/' },
        { ripple: 'teal--text', logo: 'http://www.stickpng.com/assets/images/58482e09cef1014c0b5e4a65.png', name: 'SnapSVG', to: 'http://snapsvg.io/' },
        { ripple: 'white--text', logo: 'https://www.jqueryscript.net/images/SVG-Path-Animation-Plugin-with-jQuery-Lazy-Line-Painter.jpg', name: 'Lazy Line Painter', to: 'http://lazylinepainter.info/' },
        { ripple: 'pink--text', logo: 'http://svgjs.com/assets/images/logo-svg-js-01d.png', name: 'SVG.js', to: 'http://svgjs.com/' },
        { ripple: 'orange--text', logo: 'http://maxcdn.webappers.com/img/2014/11/walkway-js.jpg', name: 'Walkway.js', to: 'https://www.connoratherton.com/walkway' }
      ]
    },
    { name: 'Hosting',
      description: 'Put your project on the web',
      id: 'hosting',
      leafs: [
        { ripple: 'amber--text', logo: 'https://firebase.google.com/_static/images/firebase/touchicon-180.png', name: 'Firebase', to: '/firease' },
        { ripple: 'red--text', logo: 'https://cdn.worldvectorlogo.com/logos/aws-s3.svg', name: 'Amazon S3', to: '/s3' },
        { ripple: 'amber--text', logo: 'https://cdn.worldvectorlogo.com/logos/aws-ec2.svg', name: 'Amazon EC2', to: '/s3' },
        { ripple: 'blue--text', logo: 'https://www.bluehost.com/blog/wp-content/uploads/2017/07/logo5.png', name: 'Bluehost', to: '/bluehost' },
        { ripple: 'teal--text', logo: 'https://www.netlify.com/img/press/logos/logomark.png', name: 'Netlify', to: '/netllify' }
      ]
    },
    { name: 'Apps',
      description: 'Create cross-platform apps using web development skill',
      id: 'apps',
      leafs: [
        { ripple: 'blue--text', logo: 'https://cdn-images-1.medium.com/max/1200/1*5-aoK8IBmXve5whBQM90GA.png', name: 'Flutter', href: 'https://flutter.io/' },
        { ripple: 'black-text', logo: 'https://lh3.googleusercontent.com/s4KD6rLbGKZz-q9YzfVt_FgSk_q2yt-Jp6Al-KY14hAaVW2IFX_QOj56iC8lJoamECs=w300', name: 'Ionic DevApp', href: 'https://ionicframework.com/' },
        { ripple: 'indigo--text', logo: 'https://pbs.twimg.com/profile_images/730268134460903424/8WOgriUU_400x400.jpg', name: 'Electron', href: 'https://electronjs.org/' },
        { ripple: 'blue--text', logo: 'https://d2odgkulk9w7if.cloudfront.net/images/default-source/default-album/nativescript.png?sfvrsn=69909fe_0', name: 'NativeScript', href: 'https://www.nativescript.org/' },
        { ripple: 'teal--text', logo: 'https://avatars1.githubusercontent.com/u/32681046?s=280&v=4', name: 'NS-Vue', href: 'https://nativescript-vue.org/' },
        { ripple: 'light-blue--text', logo: 'https://cdn-images-1.medium.com/max/358/1*JGQP6WjsRwiiLTNPiCAH5A.png', name: 'Weex', href: 'https://weex.incubator.apache.org/' },
        { ripple: 'red--text', logo: 'https://s3.amazonaws.com/media-p.slid.es/uploads/344767/images/2769652/g7.png', name: 'Onsen UI', href: 'https://onsen.io/', }
      ]
    },
    { name: 'Tools',
      description: 'Definitely check theese out',
      id: 'tools',
      leafs: [
        { ripple: 'orange--text', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Circle-icons-keyboard.svg/1024px-Circle-icons-keyboard.svg.png', name: 'Typing', to: '/typing' },
        { ripple: 'light-blue--text', logo: 'https://assets-cdn.github.com/images/modules/logos_page/Octocat.png', name: 'GitHub', to: '/github' },
        { ripple: 'amber--text', logo: 'https://firebase.google.com/_static/images/firebase/touchicon-180.png', name: 'Firebase', to: '/firease' },
        { ripple: 'red--text', logo: 'https://d2eip9sf3oo6c2.cloudfront.net/tags/images/000/000/188/full/npmlogo.png', name: 'NPM', href: 'https://www.npmjs.com/' },
        { ripple: 'green--text', logo: 'https://raw.githubusercontent.com/stvhwrd/icons/master/atom/Atom-no_shadows-512.png', name: 'Atom', href: 'https://atom.io/' },
        { ripple: 'white--text', logo: 'http://blog.codepen.io/wp-content/uploads/2012/06/Button-Fill-White-Large.png', name: 'CodePen', href: 'https://codepen.io/' },
        { ripple: 'light-green--text', logo: 'http://www.karlsjohnson.com/link/resources/images/w3school.png', name: 'Tryit Editor', href: 'https://www.w3schools.com/html/tryit.asp?filename=tryhtml_basic' },
        { ripple: 'blue--text', logo: 'https://cdn.iconscout.com/public/images/icon/free/png-512/jsfiddle-logo-cloud-38db5faa6163991e-512x512.png', name: 'jsFiddle', href: 'https://jsfiddle.net/' },
        { ripple: 'white--text', logo: 'https://static.jsbin.com/images/logo.png', name: 'jsBin', href: 'https://jsbin.com/' },
        { ripple: 'black--text', logo: 'https://codepen.io/juliangarnier/pen/oZNYXB/image/large.png', name: 'Animejs', href: 'http://animejs.com' },
        { ripple: 'white--text', logo: 'http://worthyofnote.co.uk/wp-content/uploads/2013/07/animate-css.jpg', name: 'Animate.css', href: 'https://daneden.github.io/animate.css/' },
        { ripple: 'cyan--text', logo: 'https://atomiks.github.io/30-seconds-of-css/e5b4b9ce166177b1bc2dc3772012e0a1.png', name: '30s of CSS', href: 'https://atomiks.github.io/30-seconds-of-css/' },
        { ripple: 'pink--text', logo: 'https://1001freedownloads.s3.amazonaws.com/vector/thumb/74145/iOS_7_Icon_Template.png', name: 'Popmotion', href: 'https://popmotion.io/' }
      ]
    },
    { name: 'Communities',
      description: 'Explore, discover and ask questions',
      id: 'communities',
      leafs: [
        { ripple: 'amber--text', logo: 'https://i.stack.imgur.com/GKbCl.png', name: 'Stack Overflow', href: 'https://stackoverflow.com/' },
        { ripple: 'black--text', logo: 'https://jeremyblaze.com/assets/img/medium-square.png', name: 'Medium', href: 'https://medium.com' },
        { ripple: 'lime--text', logo: 'http://www.lukashejtmanek.cz/assets/img/symbol_transparent.png', name: 'HackerRank', href: 'https://www.hackerrank.com/dashboard' },
        { ripple: 'blue--text', logo: 'http://www.stickpng.com/assets/images/5847ebc2cef1014c0b5e4857.png', name: 'Codrops', href: 'https://tympanus.net/codrops/category/tutorials/' },
        { ripple: 'white--text', logo: 'https://pbs.twimg.com/profile_images/868061114160099328/BD0P3vsp_400x400.jpg', name: 'Tutorialzine', href: 'https://tutorialzine.com/' },
        { ripple: 'blue--text', logo: 'https://static1.squarespace.com/static/564cbcb2e4b0741cdb668fe2/t/56b8c853d51cd41553c43507/1454950492725/StackShare.png', name: 'StackShare', href: 'https://stackshare.io/' },
        { ripple: 'light-blue--text', logo: 'https://avatars2.githubusercontent.com/u/15895995?s=280&v=4', name: 'Coligo', href: 'https://coligo.io' },
        { ripple: 'black--text', logo: 'https://1001freedownloads.s3.amazonaws.com/vector/thumb/74145/iOS_7_Icon_Template.png', name: 'SitePoint', href: 'https://sitepoint.com' },
        { ripple: 'teal--text', logo: 'https://1001freedownloads.s3.amazonaws.com/vector/thumb/74145/iOS_7_Icon_Template.png', name: 'Coursetro', href: 'https://coursetro.com' }

      ]
    }
  ]

  },
  mutations: {},
  actions: {},
  getters: {
    openedLeaf (state) {
      return (leafTo) => {
        return state.branches[0].leafs.find((leaf) => {
          return leaf.to === leafTo
        })||
        state.branches[1].leafs.find((leaf) => {
          return leaf.to === leafTo
        })||
        state.branches[2].leafs.find((leaf) => {
          return leaf.to === leafTo
        })||
        state.branches[3].leafs.find((leaf) => {
          return leaf.to === leafTo
        })||
        state.branches[4].leafs.find((leaf) => {
          return leaf.to === leafTo
        })||
        state.branches[5].leafs.find((leaf) => {
          return leaf.to === leafTo
        })||
        state.branches[6].leafs.find((leaf) => {
          return leaf.to === leafTo
        })||
        state.branches[7].leafs.find((leaf) => {
          return leaf.to === leafTo
        })||
        state.branches[8].leafs.find((leaf) => {
          return leaf.to === leafTo
        })||
        state.branches[9].leafs.find((leaf) => {
          return leaf.to === leafTo
        })||
        state.branches[10].leafs.find((leaf) => {
          return leaf.to === leafTo
        })
      }
    },
    branches (state) {
      return state.branches
    }
  }
}
